# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the pareto set, or the convex hull of the input data
#' @param idealPoints ...
#' @export
findParetoSet <- function(idealPoints) {
    .Call(`_MinimumRcpp_findParetoSet`, idealPoints)
}

#' Return k intersection
#' @param polyList An R list containing DataFrames with 2 columns names 'x' and 'y' representing polygon points
#' @param k Number of intersections user is looking for
#' @param epsilon Error tolerance
#' @export
kintersection <- function(polyList, k, epsilon) {
    .Call(`_MinimumRcpp_kintersection`, polyList, k, epsilon)
}

