# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Does something
#' @param i something
kintersection <- function(i) {
    .Call(`_MinimumRcpp_kintersection`, i)
}

#' Does something
#' @param i something
inner <- function(i) {
    .Call(`_MinimumRcpp_inner`, i)
}

